### PR TITLE
fixed failed unit test if cuQuantum is not available

### LINKED ISSUE #615: QR tries to call cuQantum even when compiled without cuQuantum support
If I compile without cuQuantum support, the test `linalg_Test.gpu_BkUt_Qr1` fails:

```
Test project Cytnx/build
    Start 915: linalg_Test.gpu_BkUt_Qr1
1/1 Test #915: linalg_Test.gpu_BkUt_Qr1 .........***Failed    0.71 sec
Running main() from /home/conda/feedstock_root/build_artifacts/gtest-split_1748319942332/work/googletest/src/gtest_main.cc
Note: Google Test filter = linalg_Test.gpu_BkUt_Qr1
[==========] Running 1 test from 1 test suite.
[----------] Global test environment set-up.
[----------] 1 test from linalg_Test
[ RUN      ] linalg_Test.gpu_BkUt_Qr1

# Cytnx error occur at std::vector<cytnx::Tensor> cytnx::linalg::Qr(const cytnx::Tensor&, const bool&)
# error: [QR] fatal error,try to call the cuQuantum section without cuQuantum support.

# file : Cytnx/src/linalg/Qr.cpp (78)
Stack trace:
Cytnx/build/tests/gpu/gpu_test_main(+0x9e9f38) [0x5585d0f68f38]
Cytnx/build/tests/gpu/gpu_test_main(+0x75a57c) [0x5585d0cd957c]
Cytnx/build/tests/gpu/gpu_test_main(+0x75c9ad) [0x5585d0cdb9ad]
Cytnx/build/tests/gpu/gpu_test_main(+0x68326c) [0x5585d0c0226c]
anaconda3/envs/cytnx_dev/lib/libgtest.so.1.17.0(_ZN7testing8internal35HandleExceptionsInMethodIfSupportedINS_4TestEvEET0_PT_MS4_FS3_vEPKc+0x4e) [0x7f744458b1ae]
anaconda3/envs/cytnx_dev/lib/libgtest.so.1.17.0(_ZN7testing4Test3RunEv+0xe1) [0x7f744458b481]
anaconda3/envs/cytnx_dev/lib/libgtest.so.1.17.0(_ZN7testing8TestInfo3RunEv+0x177) [0x7f744458b827]
anaconda3/envs/cytnx_dev/lib/libgtest.so.1.17.0(_ZN7testing9TestSuite3RunEv+0x1f6) [0x7f744458bc66]
anaconda3/envs/cytnx_dev/lib/libgtest.so.1.17.0(_ZN7testing8internal12UnitTestImpl11RunAllTestsEv+0x5b3) [0x7f744459a293]
anaconda3/envs/cytnx_dev/lib/libgtest.so.1.17.0(_ZN7testing8UnitTest3RunEv+0x7d) [0x7f744458be2d]
unknown file: Failure
C++ exception with description "
# Cytnx error occur at std::vector<cytnx::Tensor> cytnx::linalg::Qr(const cytnx::Tensor&, const bool&)
# error: [QR] fatal error,try to call the cuQuantum section without cuQuantum support.

# file : Cytnx/src/linalg/Qr.cpp (78)" thrown in the test body.

[  FAILED  ] linalg_Test.gpu_BkUt_Qr1 (600 ms)
[----------] 1 test from linalg_Test (600 ms total)

[----------] Global test environment tear-down
[==========] 1 test from 1 test suite ran. (600 ms total)
[  PASSED  ] 0 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] linalg_Test.gpu_BkUt_Qr1

 1 FAILED TEST


0% tests passed, 1 tests failed out of 1

Total Test time (real) =   0.72 sec

The following tests FAILED:
	915 - linalg_Test.gpu_BkUt_Qr1 (Failed)
Errors while running CTest
```

### PR DESCRIPTION
**Pull request by manuschneider**
fixes #615

### CODE REVIEW

File: tests/gpu/linalg_test/linalg_test.cpp [hunk 1]
```diff
@@ -75,10 +75,13 @@ TEST_F(linalg_Test, gpu_BkUt_Svd_truncate3) {
 // }
 
 TEST_F(linalg_Test, gpu_BkUt_Qr1) {
+#ifdef UNI_CUQUANTUM
```
Comment (IvanaGyro) [inline tests/gpu/linalg_test/linalg_test.cpp:78]: Should it be `#ifndef`?

**Review by IvanaGyro — APPROVED** [review]
